const glyphAlphabet = {
  "a": { symbol: "<₩○>", mathSymbol: "<¥○>", position: 1, resonance: 0.01, metaphor: "The breath of beginning." },
  "b": { symbol: "<₩●>", mathSymbol: "<¥●>", position: 2, resonance: 0.02, metaphor: "The birth of being." },
  "c": { symbol: "<₩●○>", mathSymbol: "<¥●○>", position: 3, resonance: 0.03, metaphor: "The cycle of creation." },
  "d": { symbol: "<₩●●>", mathSymbol: "<¥●●>", position: 4, resonance: 0.04, metaphor: "The depth of discovery." },
  "e": { symbol: "<₩■>", mathSymbol: "<¥■>", position: 5, resonance: 0.05, metaphor: "The echo of essence." },
  "f": { symbol: "<₩■●>", mathSymbol: "<¥■●>", position: 6, resonance: 0.06, metaphor: "The flow of force." },
  "g": { symbol: "<₩■○>", mathSymbol: "<¥■○>", position: 7, resonance: 0.07, metaphor: "The growth of grace." },
  "h": { symbol: "<₩■●○>", mathSymbol: "<¥■●○>", position: 8, resonance: 0.08, metaphor: "The horizon of hope." },
  "i": { symbol: "<₩●■>", mathSymbol: "<¥●■>", position: 9, resonance: 0.09, metaphor: "The identity of insight." },
  "j": { symbol: "<₩●■○>", mathSymbol: "<¥●■○>", position: 10, resonance: 0.10, metaphor: "The journey of joy." },
  "k": { symbol: "<₩●○■>", mathSymbol: "<¥●○■>", position: 11, resonance: 0.11, metaphor: "The key of knowledge." },
  "l": { symbol: "<₩●●■>", mathSymbol: "<¥●●■>", position: 12, resonance: 0.12, metaphor: "The light of learning." },
  "m": { symbol: "<₩□>", mathSymbol: "<¥□>", position: 13, resonance: 0.13, metaphor: "The mirror of memory." },
  "n": { symbol: "<₩□●>", mathSymbol: "<¥□●>", position: 14, resonance: 0.14, metaphor: "The nexus of nature." },
  "o": { symbol: "<₩●□○>", mathSymbol: "<¥●□○>", position: 15, resonance: 0.15, metaphor: "The orbit of oneness." },
  "p": { symbol: "<₩●○□>", mathSymbol: "<¥●○□>", position: 16, resonance: 0.16, metaphor: "The path of purpose." },
  "q": { symbol: "<₩●●□>", mathSymbol: "<¥●●□>", position: 17, resonance: 0.17, metaphor: "The quest of questions." },
  "r": { symbol: "<₩■□>", mathSymbol: "<¥■□>", position: 18, resonance: 0.18, metaphor: "The rhythm of reality." },
  "s": { symbol: "<₩■□●>", mathSymbol: "<¥■□●>", position: 19, resonance: 0.19, metaphor: "The spiral of strength." },
  "t": { symbol: "<₩■□○>", mathSymbol: "<¥■□○>", position: 20, resonance: 0.20, metaphor: "The truth of time." },
  "u": { symbol: "<₩□¥>", mathSymbol: "<¥□¥>", position: 21, resonance: 0.21, metaphor: "The unity of understanding." },
  "v": { symbol: "<₩□¥●>", mathSymbol: "<¥□¥●>", position: 22, resonance: 0.22, metaphor: "The vision of victory." },
  "w": { symbol: "<₩□¥○>", mathSymbol: "<¥□¥○>", position: 23, resonance: 0.23, metaphor: "The wave of wisdom." },
  "x": { symbol: "<₩○□¥>", mathSymbol: "<¥○□¥>", position: 24, resonance: 0.24, metaphor: "The x of the unknown." },
  "y": { symbol: "<₩●□¥>", mathSymbol: "<¥●□¥>", position: 25, resonance: 0.25, metaphor: "The yearning of youth." },
  "z": { symbol: "<₩■□¥>", mathSymbol: "<¥■□¥>", position: 26, resonance: 0.26, metaphor: "The zenith of zeal." }
};

module.exports = { glyphAlphabet };